# -*- coding: utf-8 -*-
"""Segmentación A-Scan en bucle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QS6RBkx5gHtxhsxUUeWVzKYtMq6kp68

Primero, cargamos librerías:
"""

import numpy as np

def dimensionfractal(imagen):
    sum_rows = np.sum(imagen,axis=0)
    sum_cols = np.sum(imagen,axis=1)
    iniciocolumnas=0
    finalcolumnas=0
    iniciofilas=0
    finalfilas=0
    for i in range(len(sum_rows)-1):
        if(sum_rows[i]==0 and sum_rows[i+1]!=0):
            iniciofilas=i+1
        elif(sum_rows[i]!=0 and sum_rows[i+1]==0):
            finalfilas=i
    for i in range(len(sum_cols)-1):
        if(sum_cols[i]==0 and sum_cols[i+1]!=0):
            iniciocolumnas=i+1
        elif(sum_cols[i]!=0 and sum_cols[i+1]==0): #Busco inicio y final de la curva barriendo en filas y luego en columnas. No son bucles anidados.
            finalcolumnas=i+1
    if (finalcolumnas==0):
        finalcolumnas=imagen.shape[1]
    if (finalfilas==0):
        finalfilas=imagen.shape[0]
    tamano=[finalfilas-iniciofilas,finalcolumnas-iniciocolumnas]
    lado=np.max(tamano)
    curva=imagen[iniciocolumnas:iniciocolumnas+lado,iniciofilas:iniciofilas+lado]
    perimetro=curva.sum() #La curva ha de estar expresada como una máscara de ceros y unos, o esto se calculará mal.
    return(np.log(perimetro)/np.log(lado))